name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync fork
        uses: tgymnich/fork-sync@e905b254d56ebb367514cd05fa96bf7516bd2a5a
